create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  username text,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  year text,
  poster_path text,
  vote_average numeric(3,1) default 0,
  added_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, tmdb_id)
);

create table if not exists watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  season integer,
  episode integer,
  duration_watched integer default 0,
  watched_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists watch_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  season integer,
  episode integer,
  progress_seconds integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, tmdb_id)
);

create table if not exists user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade unique not null,
  device text default 'laptop',
  provider text default 'vidsrccc',
  auto_play boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table profiles enable row level security;
alter table collections enable row level security;
alter table watch_history enable row level security;
alter table watch_progress enable row level security;
alter table user_settings enable row level security;

create policy "Profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can manage own collections" on collections for all using (auth.uid() = user_id);
create policy "Users can manage own history" on watch_history for all using (auth.uid() = user_id);
create policy "Users can manage own progress" on watch_progress for all using (auth.uid() = user_id);
create policy "Users can manage own settings" on user_settings for all using (auth.uid() = user_id);
