create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  username text,
  avatar_url text,
  avatar_color text,
  is_admin boolean default false,
  is_banned boolean default false,
  ban_reason text,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  year text,
  poster_path text,
  vote_average numeric(3,1) default 0,
  added_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, tmdb_id)
);

create table if not exists watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  season integer,
  episode integer,
  duration_watched integer default 0,
  poster_path text,
  vote_average numeric(3,1) default 0,
  year text,
  watched_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, tmdb_id)
);

create table if not exists watch_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  season integer,
  episode integer,
  progress_seconds integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, tmdb_id)
);

create table if not exists user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade unique not null,
  device text default 'laptop',
  provider text default 'videasy',
  auto_play boolean default true,
  beta_ui boolean default false,
  folders jsonb default '[]',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists watch_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  season integer,
  episode integer,
  started_at timestamp with time zone default timezone('utc'::text, now()),
  ended_at timestamp with time zone,
  duration_seconds integer default 0
);

alter table profiles enable row level security;
alter table collections enable row level security;
alter table watch_history enable row level security;
alter table watch_progress enable row level security;
alter table user_settings enable row level security;
alter table watch_sessions enable row level security;

create policy "Users can read own profile" on profiles for select using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can manage own collections" on collections for all using (auth.uid() = user_id);
create policy "Users can manage own history" on watch_history for all using (auth.uid() = user_id);
create policy "Users can manage own progress" on watch_progress for all using (auth.uid() = user_id);
create policy "Users can manage own settings" on user_settings for all using (auth.uid() = user_id);
create policy "Users can manage own sessions" on watch_sessions for all using (auth.uid() = user_id);

-- Auto-create profile on auth signup (bulletproof: works even if client-side createProfile fails)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, created_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    timezone('utc'::text, now())
  );
  return new;
end;
$$ language plpgsql security definer;

-- Only create the trigger if it doesn't already exist
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'on_auth_user_created'
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end $$;
