-- Lossless, account-scoped synchronization for collections and watch history.

alter table public.collections add column if not exists folder text;

alter table public.collections
  drop constraint if exists collections_user_id_tmdb_id_key;
alter table public.collections
  add constraint collections_user_id_tmdb_id_media_type_key
  unique (user_id, tmdb_id, media_type);

alter table public.watch_history
  drop constraint if exists watch_history_user_id_tmdb_id_key;
alter table public.watch_history
  add constraint watch_history_user_id_tmdb_id_media_type_key
  unique (user_id, tmdb_id, media_type);

create table if not exists public.user_data_tombstones (
  user_id uuid not null references auth.users(id) on delete cascade,
  data_type text not null check (data_type in ('collection', 'history')),
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  deleted_at timestamptz not null default now(),
  primary key (user_id, data_type, tmdb_id, media_type)
);

alter table public.user_data_tombstones enable row level security;
revoke all on public.user_data_tombstones from anon;
grant select, insert, update, delete on public.user_data_tombstones to authenticated;

drop policy if exists "Users can manage own data tombstones" on public.user_data_tombstones;
create policy "Users can manage own data tombstones"
on public.user_data_tombstones
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create table if not exists private.user_data_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);
revoke all on private.user_data_backups from public, anon, authenticated;

create or replace function public.backup_my_user_data()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller uuid := auth.uid();
  backup_id bigint;
begin
  if caller is null then
    raise exception 'Authentication required';
  end if;

  select id into backup_id
  from private.user_data_backups
  where user_id = caller and created_at > now() - interval '24 hours'
  order by created_at desc
  limit 1;

  if backup_id is null then
    insert into private.user_data_backups (user_id, snapshot)
    values (caller, jsonb_build_object(
      'collections', coalesce((select jsonb_agg(to_jsonb(c) - 'user_id') from public.collections c where c.user_id = caller), '[]'::jsonb),
      'watch_history', coalesce((select jsonb_agg(to_jsonb(h) - 'user_id') from public.watch_history h where h.user_id = caller), '[]'::jsonb),
      'watch_progress', coalesce((select jsonb_agg(to_jsonb(p) - 'user_id') from public.watch_progress p where p.user_id = caller), '[]'::jsonb),
      'created_at', now()
    ))
    returning id into backup_id;

    delete from private.user_data_backups
    where user_id = caller
      and id not in (
        select id from private.user_data_backups
        where user_id = caller
        order by created_at desc
        limit 30
      );
  end if;

  return backup_id;
end;
$$;

revoke all on function public.backup_my_user_data() from public, anon;
grant execute on function public.backup_my_user_data() to authenticated;
