-- OpenCloud owner-only Dev panel, presence, access control, and audit trail.
-- The owner is provisioned after this migration with:
--   select private.provision_dev_owner('<owner email>');
-- Never commit the real owner email to this repository.

create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text not null,
  username text,
  avatar_url text,
  avatar_color text,
  is_admin boolean default false,
  is_banned boolean default false,
  ban_reason text,
  last_seen_at timestamptz,
  created_at timestamptz default now()
);
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists avatar_color text;
alter table public.profiles add column if not exists is_admin boolean default false;
alter table public.profiles add column if not exists is_banned boolean default false;
alter table public.profiles add column if not exists ban_reason text;
alter table public.profiles add column if not exists last_seen_at timestamptz;

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  year text,
  poster_path text,
  vote_average numeric(3,1) default 0,
  added_at timestamptz default now(),
  unique(user_id, tmdb_id)
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  season integer,
  episode integer,
  duration_watched integer default 0,
  poster_path text,
  vote_average numeric(3,1) default 0,
  year text,
  watched_at timestamptz default now(),
  unique(user_id, tmdb_id)
);

create table if not exists public.watch_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  season integer,
  episode integer,
  progress_seconds integer default 0,
  updated_at timestamptz default now(),
  unique(user_id, tmdb_id)
);

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade unique not null,
  device text default 'laptop',
  provider text default 'videasy',
  auto_play boolean default true,
  beta_ui boolean default false,
  folders jsonb default '[]'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.watch_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  season integer,
  episode integer,
  started_at timestamptz default now(),
  ended_at timestamptz,
  duration_seconds integer default 0
);

alter table public.profiles enable row level security;
alter table public.collections enable row level security;
alter table public.watch_history enable row level security;
alter table public.watch_progress enable row level security;
alter table public.user_settings enable row level security;
alter table public.watch_sessions enable row level security;

revoke all on public.profiles, public.collections, public.watch_history,
  public.watch_progress, public.user_settings, public.watch_sessions from anon;
grant select, insert, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.collections to authenticated;
grant select, insert, update, delete on public.watch_history to authenticated;
grant select, insert, update, delete on public.watch_progress to authenticated;
grant select, insert, update, delete on public.user_settings to authenticated;
grant select, insert, update, delete on public.watch_sessions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, email, username, created_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    now()
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end;
$$;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.dev_owners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  expected_email text not null,
  created_at timestamptz not null default now(),
  constraint dev_owners_email_normalized check (expected_email = lower(btrim(expected_email)))
);

create table if not exists private.account_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state text not null default 'active' check (state in ('active', 'suspended')),
  reason text not null default '',
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id)
);

create table if not exists private.dev_audit_log (
  id bigint generated always as identity primary key,
  actor_user_id uuid not null references auth.users(id),
  target_user_id uuid not null references auth.users(id),
  action text not null check (action in ('suspend', 'restore')),
  reason text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.app_installations (
  install_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  app_version text not null,
  platform text not null,
  architecture text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists app_installations_user_id_idx
  on public.app_installations(user_id);
create index if not exists app_installations_last_seen_idx
  on public.app_installations(last_seen_at desc);
create index if not exists dev_audit_log_target_idx
  on private.dev_audit_log(target_user_id, created_at desc);

alter table public.app_installations enable row level security;

drop policy if exists "Users can read own installations" on public.app_installations;
create policy "Users can read own installations"
  on public.app_installations for select
  using (auth.uid() = user_id);

revoke all on public.app_installations from anon, authenticated;
grant select on public.app_installations to authenticated;

create or replace function private.provision_dev_owner(p_email text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_email text := lower(btrim(p_email));
begin
  select id into v_user_id
  from auth.users
  where lower(email) = v_email
    and email_confirmed_at is not null;

  if v_user_id is null then
    raise exception 'No confirmed Supabase account exists for that email';
  end if;

  insert into private.dev_owners(user_id, expected_email)
  values (v_user_id, v_email)
  on conflict (user_id) do update
    set expected_email = excluded.expected_email;

  delete from private.dev_owners where user_id <> v_user_id;
  return v_user_id;
end;
$$;
revoke all on function private.provision_dev_owner(text) from public, anon, authenticated;

create or replace function private.is_dev_owner(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from private.dev_owners owners
    join auth.users users on users.id = owners.user_id
    where owners.user_id = p_user_id
      and users.email_confirmed_at is not null
      and lower(users.email) = owners.expected_email
  );
$$;
revoke all on function private.is_dev_owner(uuid) from public, anon, authenticated;

create or replace function private.assert_dev_owner()
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not private.is_dev_owner(auth.uid()) then
    raise exception 'Dev access denied' using errcode = '42501';
  end if;
end;
$$;
revoke all on function private.assert_dev_owner() from public, anon, authenticated;

create or replace function public.account_is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select auth.uid() is not null and coalesce((
    select access.state = 'active'
    from private.account_access access
    where access.user_id = auth.uid()
  ), true);
$$;
revoke all on function public.account_is_active() from public, anon;
grant execute on function public.account_is_active() to authenticated;

create or replace function public.get_my_access()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when auth.uid() is null then jsonb_build_object('state', 'signed_out', 'reason', '', 'isOwner', false)
    else jsonb_build_object(
      'state', coalesce(access.state, 'active'),
      'reason', coalesce(access.reason, ''),
      'isOwner', private.is_dev_owner(auth.uid())
    )
  end
  from (select 1) seed
  left join private.account_access access on access.user_id = auth.uid();
$$;
revoke all on function public.get_my_access() from public, anon;
grant execute on function public.get_my_access() to authenticated;

create or replace function public.heartbeat_installation(
  p_install_id uuid,
  p_app_version text,
  p_platform text,
  p_architecture text
)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
begin
  if auth.uid() is null or not public.account_is_active() then
    raise exception 'Active account required' using errcode = '42501';
  end if;
  if p_install_id is null then
    raise exception 'Installation ID required' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.app_installations
    where install_id = p_install_id and user_id <> auth.uid()
  ) then
    raise exception 'Installation ID belongs to another account' using errcode = '42501';
  end if;

  insert into public.app_installations(
    install_id, user_id, app_version, platform, architecture, first_seen_at, last_seen_at
  ) values (
    p_install_id,
    auth.uid(),
    left(coalesce(nullif(btrim(p_app_version), ''), 'unknown'), 32),
    left(coalesce(nullif(btrim(p_platform), ''), 'unknown'), 32),
    left(coalesce(nullif(btrim(p_architecture), ''), 'unknown'), 32),
    v_now,
    v_now
  )
  on conflict (install_id) do update set
    user_id = auth.uid(),
    app_version = excluded.app_version,
    platform = excluded.platform,
    architecture = excluded.architecture,
    last_seen_at = v_now;

  return v_now;
end;
$$;
revoke all on function public.heartbeat_installation(uuid, text, text, text) from public, anon;
grant execute on function public.heartbeat_installation(uuid, text, text, text) to authenticated;

create or replace function public.dev_summary()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  perform private.assert_dev_owner();
  select jsonb_build_object(
    'accounts', (select count(*) from auth.users),
    'installations', (select count(*) from public.app_installations),
    'onlineUsers', (
      select count(distinct user_id)
      from public.app_installations
      where last_seen_at >= now() - interval '2 minutes'
    ),
    'onlineInstallations', (
      select count(*)
      from public.app_installations
      where last_seen_at >= now() - interval '2 minutes'
    ),
    'suspended', (
      select count(*) from private.account_access where state = 'suspended'
    ),
    'generatedAt', now()
  ) into v_result;
  return v_result;
end;
$$;
revoke all on function public.dev_summary() from public, anon;
grant execute on function public.dev_summary() to authenticated;

create or replace function public.dev_list_users(
  p_query text default '',
  p_status text default 'all',
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_query text := lower(btrim(coalesce(p_query, '')));
  v_status text := lower(btrim(coalesce(p_status, 'all')));
  v_limit integer := greatest(1, least(coalesce(p_limit, 100), 200));
  v_offset integer := greatest(0, coalesce(p_offset, 0));
  v_result jsonb;
begin
  perform private.assert_dev_owner();
  if v_status not in ('all', 'online', 'offline', 'suspended') then
    raise exception 'Invalid status filter' using errcode = '22023';
  end if;

  with user_rows as (
    select
      users.id,
      coalesce(profiles.username, split_part(users.email, '@', 1), 'User') as username,
      users.email,
      users.created_at as joined_at,
      coalesce(access.state, 'active') as access_state,
      coalesce(access.reason, '') as access_reason,
      private.is_dev_owner(users.id) as is_owner,
      installs.installation_count,
      installs.last_seen_at,
      installs.latest_version,
      installs.latest_platform,
      installs.latest_architecture,
      coalesce(installs.last_seen_at >= now() - interval '2 minutes', false) as is_online
    from auth.users users
    left join public.profiles profiles on profiles.id = users.id
    left join private.account_access access on access.user_id = users.id
    left join lateral (
      select
        count(*)::integer as installation_count,
        max(i.last_seen_at) as last_seen_at,
        (array_agg(i.app_version order by i.last_seen_at desc))[1] as latest_version,
        (array_agg(i.platform order by i.last_seen_at desc))[1] as latest_platform,
        (array_agg(i.architecture order by i.last_seen_at desc))[1] as latest_architecture
      from public.app_installations i
      where i.user_id = users.id
    ) installs on true
    where (
      v_query = ''
      or lower(coalesce(users.email, '')) like '%' || v_query || '%'
      or lower(coalesce(profiles.username, '')) like '%' || v_query || '%'
    )
  ), filtered as (
    select * from user_rows
    where v_status = 'all'
      or (v_status = 'online' and is_online)
      or (v_status = 'offline' and not is_online and access_state <> 'suspended')
      or (v_status = 'suspended' and access_state = 'suspended')
  )
  select jsonb_build_object(
    'total', (select count(*) from filtered),
    'users', coalesce((
      select jsonb_agg(to_jsonb(page) order by page.joined_at desc)
      from (
        select * from filtered
        order by joined_at desc
        limit v_limit offset v_offset
      ) page
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;
revoke all on function public.dev_list_users(text, text, integer, integer) from public, anon;
grant execute on function public.dev_list_users(text, text, integer, integer) to authenticated;

create or replace function public.dev_user_detail(p_user_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  perform private.assert_dev_owner();
  if not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'User not found' using errcode = 'P0002';
  end if;

  select jsonb_build_object(
    'installations', coalesce((
      select jsonb_agg(jsonb_build_object(
        'installId', installs.install_id,
        'appVersion', installs.app_version,
        'platform', installs.platform,
        'architecture', installs.architecture,
        'firstSeenAt', installs.first_seen_at,
        'lastSeenAt', installs.last_seen_at,
        'isOnline', installs.last_seen_at >= now() - interval '2 minutes'
      ) order by installs.last_seen_at desc)
      from public.app_installations installs
      where installs.user_id = p_user_id
    ), '[]'::jsonb),
    'audit', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', audit.id,
        'action', audit.action,
        'reason', audit.reason,
        'createdAt', audit.created_at
      ) order by audit.created_at desc)
      from (
        select * from private.dev_audit_log
        where target_user_id = p_user_id
        order by created_at desc
        limit 50
      ) audit
    ), '[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;
revoke all on function public.dev_user_detail(uuid) from public, anon;
grant execute on function public.dev_user_detail(uuid) to authenticated;

create or replace function public.dev_suspend_user(p_user_id uuid, p_reason text default '')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reason text := left(btrim(coalesce(p_reason, '')), 500);
  v_audit_id bigint;
begin
  perform private.assert_dev_owner();
  if p_user_id is null or not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'User not found' using errcode = 'P0002';
  end if;
  if p_user_id = auth.uid() or private.is_dev_owner(p_user_id) then
    raise exception 'The owner account cannot be suspended' using errcode = '42501';
  end if;

  insert into private.account_access(user_id, state, reason, changed_at, changed_by)
  values (p_user_id, 'suspended', v_reason, now(), auth.uid())
  on conflict (user_id) do update set
    state = 'suspended', reason = excluded.reason,
    changed_at = excluded.changed_at, changed_by = excluded.changed_by;

  update public.profiles
  set is_banned = true, ban_reason = v_reason, last_seen_at = null
  where id = p_user_id;

  delete from auth.sessions where user_id = p_user_id;

  insert into private.dev_audit_log(actor_user_id, target_user_id, action, reason)
  values (auth.uid(), p_user_id, 'suspend', v_reason)
  returning id into v_audit_id;

  return jsonb_build_object('userId', p_user_id, 'state', 'suspended', 'auditId', v_audit_id);
end;
$$;
revoke all on function public.dev_suspend_user(uuid, text) from public, anon;
grant execute on function public.dev_suspend_user(uuid, text) to authenticated;

create or replace function public.dev_restore_user(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_audit_id bigint;
begin
  perform private.assert_dev_owner();
  if p_user_id is null or not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'User not found' using errcode = 'P0002';
  end if;

  insert into private.account_access(user_id, state, reason, changed_at, changed_by)
  values (p_user_id, 'active', '', now(), auth.uid())
  on conflict (user_id) do update set
    state = 'active', reason = '', changed_at = excluded.changed_at, changed_by = excluded.changed_by;

  update public.profiles
  set is_banned = false, ban_reason = ''
  where id = p_user_id;

  insert into private.dev_audit_log(actor_user_id, target_user_id, action, reason)
  values (auth.uid(), p_user_id, 'restore', '')
  returning id into v_audit_id;

  return jsonb_build_object('userId', p_user_id, 'state', 'active', 'auditId', v_audit_id);
end;
$$;
revoke all on function public.dev_restore_user(uuid) from public, anon;
grant execute on function public.dev_restore_user(uuid) to authenticated;

-- Profiles contain personal data. A signed-in user may only see their own row.
drop policy if exists "Profiles are viewable by everyone" on public.profiles;
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id and public.account_is_active());

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id and public.account_is_active());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id and public.account_is_active())
  with check (auth.uid() = id and public.account_is_active());

revoke update on public.profiles from authenticated;
grant update (email, username, avatar_url, avatar_color, last_seen_at) on public.profiles to authenticated;

-- Keep the existing data model, but make suspension effective at the database boundary.
drop policy if exists "Users can manage own collections" on public.collections;
create policy "Users can manage own collections" on public.collections
  for all using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

drop policy if exists "Users can manage own history" on public.watch_history;
create policy "Users can manage own history" on public.watch_history
  for all using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

drop policy if exists "Users can manage own progress" on public.watch_progress;
create policy "Users can manage own progress" on public.watch_progress
  for all using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

drop policy if exists "Users can manage own settings" on public.user_settings;
create policy "Users can manage own settings" on public.user_settings
  for all using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

drop policy if exists "Users can manage own sessions" on public.watch_sessions;
create policy "Users can manage own sessions" on public.watch_sessions
  for all using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

comment on table public.app_installations is
  'Minimal signed-in installation presence. No hardware fingerprint, IP address, token, or viewing activity is stored.';
